### PR TITLE
Proxies

### PR DESCRIPTION
**Pull request by JohnCoene**
Hi Joshua,

Thanks for highcharter!

Further our Twitter chat I thought I'd do a PR to implement a proxy.

```r
library(shiny)

data("diamonds", package = "ggplot2")

ui <- fluidPage(
  actionButton("hide", "Hide"),
  highchartOutput("hc")
)

server <- function(input, output, session){
  output$hc <- renderHighchart({
    hchart(diamonds$price, color = "#B71C1C", name = "Price") %>% 
      hc_title(text = "You can zoom me")
  })
  
  observeEvent(input$hide, {
    highchartProxy("hc") %>%  # hide first serie on button click
      hc_hide(
        list(chart = list(polar = TRUE))
      )
  })
}

if(interactive()) shinyApp(ui, server)
```

This is really only meant to be an example, I'm sure a better implementation is possible for highcharts js. 

Essentially just created a `highchartProxy` to generate a proxy of a chart and implemented the [hide](https://api.highcharts.com/class-reference/Highcharts.Series#hide) method to hide the first serie of the chart.

Let me know what you think, happy to help.

### CODE REVIEW

**Comment by PaulC91** [comment]
Hi John & Joshua!

We also have a fork of highcharter we're using at @epicentre-msf with several shiny proxy functions added (not coded by me so I'm taking no credit!). We'd need to tidy it up and add documentation but let me know if you're interested in a PR.

Thanks,
Paul

**Comment by JohnCoene** [comment]
[Neat!](https://github.com/epicentre-msf/highcharter/) That'd be awesome, I'd be keen to add a few additional methods (as proxies) if @jbkunst is keen on your PR

**Comment by PaulC91** [comment]
@JohnCoene sounds good. interested to know what methods you're thinking of adding! 

One option that would be good but doesn't look to be available in our fork is to replace data with data that has different groups from the originally rendered highchart. For example if you have a line chart showing values over time for groups x and y, currently if new data is sent to the proxy this time with groups x, y and z, group z is not added to the chart, only groups x and y are updated. So it would be nice to have to option of adding/removing groups to an existing chart with the legend updating accordingly etc.

**Comment by jbkunst** [comment]
Materials:
- https://shiny.rstudio.com/articles/js-send-message.html
- https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/

epicentre-msf' highcharter
- https://github.com/epicentre-msf/highcharter/blob/master/inst/htmlwidgets/highchart.js#L151
- https://github.com/epicentre-msf/highcharter/blob/master/R/highcharter.R#L205

echarts4r
- https://github.com/JohnCoene/echarts4r/blob/master/inst/htmlwidgets/echarts4r.js#L193
- https://github.com/JohnCoene/echarts4r/blob/master/R/proxies.R

Ideas:
- `hc_add_series.highchart_Proxy` 
- `hc_rm_series.highchart_Proxy`

Other Examples of #112 
- [`addSeries`](http://api.highcharts.com/highcharts#Chart.addSeries)
- [`addPoint`](http://api.highcharts.com/highcharts#Series.addPoint)
- [`removePoint`](http://api.highcharts.com/highcharts#Series.removePoint)
- [`redraw`](http://api.highcharts.com/highcharts#Chart.redraw) and others.
- [Adding live data points](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-update/)
- [Adding user supplied points](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-click-to-add/)

**Comment by jbkunst** [comment]
Hi guys! @JohnCoene @PaulC91 

I've been working this week in the proxies and I have some _stable_ results. Obviously it needs more test but there are some functions that are working. Thanks so much  for the motivation!

If you don't mind I will add you as ctb to the package.

https://jbkunst.shinyapps.io/highcharter-proxy/

**Comment by PaulC91** [comment]
Looks great @jbkunst! thanks so much. 

In terms of ctb, you should add [Serge Balandine](https://github.com/S-Balandine) not me, as all the code in the epicentre/msf fork was his great work!

Thanks again,
Paul

**Comment by AndreasHaldIncom** [comment]
Hi guys. I'm new to this "contribution part" of GitHub and how to make formal PR. I just wanted to share some further work on the post. I've made the functions such that you can hide/show multiple series by ID with a button click. 

`library(tidyverse)
library(highcharter)
library(shiny)

hc_hide <- function (proxy, id = NULL, ...) {
  highcharter:::checkProxy(proxy)
  for (i in 1:length(id)) {
    if (getOption("highcharter.verbose")) {
      message("hcpxy_update_series")
    }
    proxy$session$sendCustomMessage(type = "highchart_hide",
                                    message = list(id = proxy$id, idSeries = id[[i]],
                                                   options = list(...)))
  }
  proxy
}

hc_show <- function (proxy, id = NULL, ...) {
  highcharter:::checkProxy(proxy)
  for (i in 1:length(id)) {
    if (getOption("highcharter.verbose")) {
      message("hcpxy_update_series")
    }
    proxy$session$sendCustomMessage(type = "highchart_show",
                                    message = list(id = proxy$id, idSeries = id[[i]],
                                                   options = list(...)))
  }
  proxy
}

ui <- fluidPage(
  actionButton("hide", "Hide"),
  actionButton("show", "Show"),
  highchartOutput("hc")
)

server <- function(input, output, session){
  output$hc <- renderHighchart({
    message("render")
    hchart(ggplot2::mpg %>% count(year, class), "column", hcaes(class, n, group = year), id = c("1999", "2008"))
  })
  
  observeEvent(input$hide, {
    highchartProxy("hc") %>%  # hide serie by id on button click
      hc_hide(id = c("2008"))
  })
  
  observeEvent(input$show, {
    highchartProxy("hc") %>%  # show serie by id on button click
      hc_show(id = c("2008"))
  })
}
if(interactive()) shinyApp(ui, server)`

Where the corresponding .js functions are as follows (which should be included in the highchart.js file in the library under the htmlwidgets folder) : 
`
  Shiny.addCustomMessageHandler('redraw', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    
    if (typeof chart != 'undefined') {
      
      chart.redraw();
      
    }
      
  });

  Shiny.addCustomMessageHandler('highchart_show', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    chart.get(msg.idSeries).show();
  });  

  Shiny.addCustomMessageHandler('highchart_hide', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    chart.get(msg.idSeries).hide();
    
  });
`

**Comment by AndreasHaldIncom** [comment]
Hi guys. I'm new to this "contribution part" of GitHub and how to make formal PR. I just wanted to share some further work on the post. I've made the functions such that you can hide/show multiple series by ID with a button click. 

```
library(tidyverse)
library(highcharter)
library(shiny)

hc_hide <- function (proxy, id = NULL, ...) {
  highcharter:::checkProxy(proxy)
  for (i in 1:length(id)) {
    if (getOption("highcharter.verbose")) {
      message("hcpxy_update_series")
    }
    proxy$session$sendCustomMessage(type = "highchart_hide",
                                    message = list(id = proxy$id, idSeries = id[[i]],
                                                   options = list(...)))
  }
  proxy
}

hc_show <- function (proxy, id = NULL, ...) {
  highcharter:::checkProxy(proxy)
  for (i in 1:length(id)) {
    if (getOption("highcharter.verbose")) {
      message("hcpxy_update_series")
    }
    proxy$session$sendCustomMessage(type = "highchart_show",
                                    message = list(id = proxy$id, idSeries = id[[i]],
                                                   options = list(...)))
  }
  proxy
}

ui <- fluidPage(
  actionButton("hide", "Hide"),
  actionButton("show", "Show"),
  highchartOutput("hc")
)

server <- function(input, output, session){
  output$hc <- renderHighchart({
    message("render")
    hchart(ggplot2::mpg %>% count(year, class), "column", hcaes(class, n, group = year), id = c("1999", "2008"))
  })
  
  observeEvent(input$hide, {
    highchartProxy("hc") %>%  # hide serie by id on button click
      hc_hide(id = c("2008"))
  })
  
  observeEvent(input$show, {
    highchartProxy("hc") %>%  # show serie by id on button click
      hc_show(id = c("2008"))
  })
}
if(interactive()) shinyApp(ui, server)
```

Where the corresponding .js functions are as follows (which should be included in the highchart.js file in the library under the htmlwidgets folder) : 
```
  Shiny.addCustomMessageHandler('redraw', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    
    if (typeof chart != 'undefined') {
      
      chart.redraw();
      
    }
      
  });

  Shiny.addCustomMessageHandler('highchart_show', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    chart.get(msg.idSeries).show();
  });  

  Shiny.addCustomMessageHandler('highchart_hide', function(msg) {
    
    var chart = $("#" + msg.id).highcharts();
    chart.get(msg.idSeries).hide();
    
  });
```

**Pull request closed without merging**
