### PR TITLE
Add support for labels via hc_labels

### PR DESCRIPTION
**Pull request by Gimperion**
I added support for HTML labels as per the Highcharts API but I think my editor deleted all the line ending white spaces in api-hc.R  :(

### CODE REVIEW

**Comment by jbkunst** [comment]
Hi @Gimperion  :)

Can you give me an example using hc_labels? Not sure how to use :/ https://api.highcharts.com/highcharts/labels

**Comment by Gimperion** [comment]
One way I've used it is adding footnotes to the visualization when you've already used hc_credits.  For use cases that require a bit of polish, a customer might want 1) a branding logo, 2) a source line, and/or 3) a footnote.

I use something like this to add additional footnotes into the visualization, while passing in left/top parameters via ...

`addFootnote <- function(x, footnote, ...){
	x %>%
		hc_labels(items=list(
			list(html=sprintf("<p>%s</p>", footnote),
				style=list(...)
			)
		))
}
`

**Comment by jbkunst** [comment]
Hi @Gimperion!

Ok, I get it. I will include the `hc_labels` function but no using via this PR due I automated the generation/documention of the API (https://github.com/jbkunst/highcharter/blob/master/dev/generate-highcharts-api.R)

**Comment by Gimperion** [comment]
Thanks!!

**Pull request closed without merging**
