### PR TITLE
Plot survival curves

### PR DESCRIPTION
**Pull request by nuno-agostinho**
I've created the function `hchart.survfit` to accept a survfit object and plot survival curves. Below you can compare the difference between using the standard `plot` function and the `hchart`.

```r
# Plot Kaplan-Meier curves
library(survival)
leukemia.surv <- survfit(Surv(time, status) ~ x, data = aml) 
plot(leukemia.surv)
hchart(leukemia.surv)
```
surv

```r
# Plot the cumulative hazard function
lsurv2 <- survfit(Surv(time, status) ~ x, aml, type='fleming') 
plot(lsurv2, fun="cumhaz")
hchart(lsurv2, fun="cumhaz")
```
cumhaz

```r
# Plot the fit of a Cox proportional hazards regression model
fit <- coxph(Surv(futime, fustat) ~ age, data = ovarian)
ovarian.surv <- survfit(fit, newdata=data.frame(age=60))
plot(ovarian.surv)
hchart(ovarian.surv, ranges = TRUE)
```
coxph

Be warned that more complex plots using CoxPH models may not work. Also, it's usual to plot survival curves with those plus sign (the ➕ from Font Awesome) as event markers. However, those markers are slightly displaced (worse: they can be displaced further when zooming). Do you know how to fix this? If Highcharts allowed to plot the plus sign, it'd be easier but they only have diamonds, circles, squares and triangles. 😞

### CODE REVIEW

**Comment by nuno-agostinho** [comment]
The checks are failing while trying to call the library survival. How can I fix this?

**Comment by jbkunst** [comment]
Hi @nuno-agostinho !

First of all thanks a lot for this. It's look great :smile: 

* Susvival package. Not sure but you need add `survival` to the suggest list in the `DESCRIPTION` file.
* In the https://travis-ci.org/jbkunst/highcharter/builds/128528870, you are missing the `...` in `hchart.survfit <- function(object, fun=NULL `. It's need to be: `hchart.survfit <- function(object, ..., fun=NULL, other = pars)`
* About the `...`. Can we add the `...` in every `hc_add_series` and  `marker <- list(list(fillColor=markerColor, symbol=markerSymbol, enabled=TRUE, ...))` ? So we can do things like: `hchart.survfit(fit, lineWidth = 2, radius = 3, symbol = 'square')`. And then remove maybe the `markerSymbol` parameter. What do you think?
* Maker: Yep the fontawesome plugin dont work nicely 100% because as you notice they show displaced. It' seems you can add your own symbol [here](http://stackoverflow.com/questions/21985319/highcharts-cross-symbol-with-fillcolor) and [here](http://stackoverflow.com/questions/27542928/extend-highcharts-renderer-symbols-to-have-plus-sign). So, are you agree if you put a highcharts default symbol as triangle or other one until I/we add this custom plus/cross symbol?
* If you remove the  `ymin=0, ymax=1` arguments what happend? The values given by `highchart`doesnt' make sense (ie negative limits)? . I want/try to make the functions the most simple (less code) possible. Because if a user are not happy with the default result they can keep modifiyng using the API: `hchart.survival(fit) %>% hc_yAxis(min = a, max = b)`
* Dont forget add `hchart.survfit` to your comments  in the `DESCRIPTION` file.

Again. Thanks so much for this nice contribution :D.

I'll wait for your reply :+1:

**Comment by nuno-agostinho** [comment]
Hi there, @jbkunst!

> About the .... Can we add the ... in every hc_add_series and marker <- list(list(fillColor=markerColor, symbol=markerSymbol, enabled=TRUE, ...)) ? So we can do things like: hchart.survfit(fit, lineWidth = 2, radius = 3, symbol = 'square'). And then remove maybe the markerSymbol parameter. What do you think?

I agree we should add `…`. I wasn't sure if I should put it just in `marker <- list(list(fillColor=markerColor, symbol=markerSymbol, enabled=TRUE, …))` so I ended up not using it at all.

I would be against removing the `markerSymbol` parameter because I'd like to have it by default when plotting this kind of plot. However, we can rename it to `symbol` to be more consistent with Highcharts.

> Maker: Yep the fontawesome plugin dont work nicely 100% because as you notice they show displaced. It' seems you can add your own symbol here and here. So, are you agree if you put a highcharts default symbol as triangle or other one until I/we add this custom plus/cross symbol?

I'll try to create a cross in that way. In the meantime, the default can be a triangle, sure.

> If you remove the ymin=0, ymax=1 arguments what happend? The values given by highchartdoesnt' make sense (ie negative limits)? . I want/try to make the functions the most simple (less code) possible. Because if a user are not happy with the default result they can keep modifiyng using the API: hchart.survival(fit) %>% hc_yAxis(min = a, max = b)

I knew this was under-explained. 😞 Survival plots with values between 0 and 1 are usually plotted between 0 (as min Y) and 1 (as max Y). This is by convention. If we have to plot values higher than 1 and/or lower than 0, than the Y max and min change accordingly.

As you said, this is confusing and maybe I'll just put the Y axis between 1 and 0 by default unless it has values outside that range. It'll be the same without the arguments `ymin` and `ymax` (1 and 0 in their place) and easy to override if the user wants it by doing `hchart.survival(fit) %>% hc_yAxis(min = a, max = b)`

**Comment by jbkunst** [comment]
Hi @nuno-agostinho !

I'm agree with you. So, to close this PR:

* Add `...` in `hc_add_series` but not in `list(list(fillColor ...`
* Rename the argument to `symbol` and use traingle as default.
* Remove the `ymin`, `ymax` arguments and set them internally.

I'll wait the changes to merge :smiley: 

Thanks again :+1:

**Comment by nuno-agostinho** [comment]
I think that's it! So the only thing missing now is to create the cross for the marker symbol. 😄

**Comment by jbkunst** [comment]
Thanks!!!

**Pull request merged**
