### PR TITLE
fix export_hc()

### LINKED ISSUE #398: export_hc(..., as = "is") does not format colors correctly
The `export_hc()` function has some hacky usage of `stringr::str_replace()`, and it sometimes causes problems.

I have a pull request almost ready that should fix this issue.

Here is a minimal example that demonstrates one problem:

```r
data("vaccines")
library("viridis")
library(highcharter)

include_states <- c("Alabama", "Alaska")
hc <- hchart(
  object = subset(vaccines, state %in% include_states),
  "heatmap", hcaes(x = year, y = state, value = count)
) %>% 
  hc_colorAxis(stops = color_stops(10, rev(inferno(10))),
               type = "logarithmic")

export_hc(hc, "test_heatmap.js", as = "is")
```

The `test_heatmap.js` file has errors. Notice that the first color is `#FCFFA4"` (it is missing the first quote `"`). It should be `"#FCFFA4"`.

```
  colorAxis: {
    stops: [
      [
        0,
        #FCFFA4"
      ],
      [
        0.1111,
        #F7D03C"
      ],
      [
        0.2222,
        #FB9A06"
      ],
```

<details>
<summary>Session Info</summary>
<pre>
Session info --------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.414)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-02-11                  

Packages ------------------------------------------------------------------------------------------------------------------------
 package     * version    date       source                          
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                  
 base        * 3.4.3      2017-12-07 local                           
 bindr         0.1        2016-11-13 CRAN (R 3.4.0)                  
 bindrcpp    * 0.2        2017-06-17 CRAN (R 3.4.0)                  
 broom         0.4.3      2017-11-20 CRAN (R 3.4.2)                  
 cli           1.0.0      2017-11-05 CRAN (R 3.4.2)                  
 colorspace    1.3-2      2016-12-14 CRAN (R 3.4.0)                  
 compiler      3.4.3      2017-12-07 local                           
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.1)                  
 curl          3.1        2017-12-12 cran (@3.1)                     
 data.table    1.10.4-3   2017-10-27 CRAN (R 3.4.2)                  
 datasets    * 3.4.3      2017-12-07 local                           
 devtools      1.13.4     2017-11-09 CRAN (R 3.4.2)                  
 digest        0.6.15     2018-01-28 cran (@0.6.15)                  
 dplyr         0.7.4      2017-09-28 CRAN (R 3.4.2)                  
 foreign       0.8-69     2017-06-22 CRAN (R 3.4.3)                  
 ggplot2       2.2.1.9000 2018-02-11 local                           
 glue          1.2.0      2017-10-29 CRAN (R 3.4.2)                  
 graphics    * 3.4.3      2017-12-07 local                           
 grDevices   * 3.4.3      2017-12-07 local                           
 grid          3.4.3      2017-12-07 local                           
 gridExtra     2.3        2017-09-09 CRAN (R 3.4.1)                  
 gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                  
 highcharter * 0.5.0.9999 2018-02-12 local                           
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                  
 htmlwidgets   1.0        2018-01-20 CRAN (R 3.4.3)                  
 igraph        1.1.2      2017-07-21 CRAN (R 3.4.1)                  
 jsonlite      1.5        2017-06-01 cran (@1.5)                     
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.3)                  
 lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.2)                  
 lubridate     1.7.2      2018-02-06 cran (@1.7.2)                   
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                  
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                  
 methods     * 3.4.3      2017-12-07 local                           
 mnormt        1.5-5      2016-10-15 CRAN (R 3.4.0)                  
 munsell       0.4.3      2016-02-13 CRAN (R 3.4.0)                  
 nlme          3.1-131    2017-02-06 CRAN (R 3.4.3)                  
 parallel      3.4.3      2017-12-07 local                           
 pillar        1.1.0      2018-01-14 cran (@1.1.0)                   
 pkgconfig     2.0.1      2017-03-21 CRAN (R 3.4.0)                  
 plyr          1.8.4      2016-06-08 CRAN (R 3.4.0)                  
 psych         1.7.8      2017-09-09 CRAN (R 3.4.2)                  
 purrr         0.2.4      2017-10-18 CRAN (R 3.4.2)                  
 quantmod      0.4-12     2017-12-10 cran (@0.4-12)                  
 R6            2.2.2      2017-06-17 cran (@2.2.2)                   
 Rcpp          0.12.15    2018-01-20 cran (@0.12.15)                 
 reshape2      1.4.3      2017-12-11 cran (@1.4.3)                   
 rlang         0.1.6.9003 2018-02-09 Github (tidyverse/rlang@616fd4d)
 rlist         0.4.6.1    2016-04-04 CRAN (R 3.4.0)                  
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.1)                  
 scales        0.5.0.9000 2017-12-01 Github (hadley/scales@d767915)  
 stats       * 3.4.3      2017-12-07 local                           
 stringi       1.1.6      2017-11-17 CRAN (R 3.4.2)                  
 stringr       1.2.0      2017-02-18 CRAN (R 3.4.0)                  
 tibble        1.4.2      2018-01-22 cran (@1.4.2)                   
 tidyr         0.8.0      2018-01-29 cran (@0.8.0)                   
 tools         3.4.3      2017-12-07 local                           
 TTR           0.23-3     2018-01-24 cran (@0.23-3)                  
 utf8          1.1.3      2018-01-03 cran (@1.1.3)                   
 utils       * 3.4.3      2017-12-07 local                           
 viridis     * 0.4.0      2017-03-27 CRAN (R 3.4.0)                  
 viridisLite * 0.3.0      2018-02-01 cran (@0.3.0)                   
 whisker       0.3-2      2013-04-28 CRAN (R 3.4.0)                  
 withr         2.1.1.9000 2017-12-20 Github (jimhester/withr@df18523)
 xts           0.10-1     2017-12-20 cran (@0.10-1)                  
 yaml          2.1.16     2017-12-12 CRAN (R 3.4.3)                  
 zoo           1.8-1      2018-01-08 cran (@1.8-1)     
</pre>
</details>

### PR DESCRIPTION
**Pull request by slowkow**
This should fix #398 

Following the advice of @jeroen at
https://github.com/jeroen/jsonlite/issues/77

Use `class(x) <- "json"` to indicate that the string should be
interpreted verbatim by `jsonlite::toJSON(..., json_verbatim = TRUE)`.

After this change, we can avoid the hacky `stringr::str_replace()` calls in
`export_hc()`. This should help to avoid bugs in javascript outputs.

### CODE REVIEW

**Comment by slowkow** [comment]
Here's an example of how the `json_verbatim` option in `jsonlite::toJSON()` works.

```r
# Example of json_verbatim
f <- "function() { console.log('you clicked') }"
jsonlite::toJSON(
  x = list(click = f),
  pretty = TRUE,
  auto_unbox = TRUE,
  json_verbatim = TRUE
)
#> {
#>   "click": "function() { console.log('you clicked') }"
#> }

class(f) <- "json"
jsonlite::toJSON(
  x = list(click = f),
  pretty = TRUE,
  auto_unbox = TRUE,
  json_verbatim = TRUE
)
#> {
#>   "click": function() { console.log('you clicked') }
#> }
```

**Comment by slowkow** [comment]
Looks like I broke a few things... I'll try to fix it soon.

**Comment by jbkunst** [comment]
Nice! Thanks so much @slowkow.

There is no problem to add you in de `DESCRIPTION` as ctb, right?

**Comment by slowkow** [comment]
I'd be very happy to be added as a contributor. Thank you!

```
person("Kamil", "Slowikowski", role = c("ctb"), comment = c(ORCID = "0000-0002-2843-6370"))
```

**Comment by slowkow** [comment]
@jbkunst I'm sorry for the mistake! It's my fault. I should have tested to make sure my code does not break things.

I don't know if there is an automated way to test that the Javascript code is embedded correctly in an interactive figure... I have a feeling that we might need to run an interactive session and manually inspect the figure.

Sorry again! I really didn't mean to make things more difficult for you.

**Comment by jbkunst** [comment]
No problem @slowkow  :wink: I  was my fault too.

Thanks for update the code!

**Pull request merged**
