### PR TITLE
Treemap update

### PR DESCRIPTION
**Pull request by alexpghayes**
This pull request is to address the following issues in the Highcharter function `hctreemap`:

* hctreemap() fails to render with cellnames repeated across levels #310
* bug in treemap when index variables have same values #32
* Does not work correctly for 3 level Treemaps #117
* hc_add_series_treemap - naming of the color value variable #98
* review/rework treemap fns #110

I've created a markdown walkthrough `dev/treemap2.Rmd` documenting a new function `hctreemap2` that I believe fixes these. Sorry this has taken me so long.

### CODE REVIEW

**Comment by jbkunst** [comment]
Hi @alexpghayes 

I'm really happy to see this :)! I will take 1 or 2 days to see the changes, and see how the functions works (I'm new to `rlang`) and see other details. 

Thank you very much! With this it's probably make a new release soon! 

Best,

**Comment by jbkunst** [comment]
And don't say sorry :sweat_smile: !

**Comment by alexpghayes** [comment]
The first half of [this blog post](https://alexpghayes.github.io/2017/gentle-non-standard-evaluation-in-dplyr-0-6/) covers all of the new `dplyr` NSE I used. I'm happy to comment the code or rewriting any sections for clarity. Probably the most useful thing to do to understand the function is to print out `treemap_df` after it's generated.

**Comment by jbkunst** [comment]
Hi @alexpghayes !!

>  I will take 1 or 2 days to see the changes,

The longest days on the entire history! So sorry! Thanks to you I will start the new release! I'll add you to the contributors in the DESCRIPTION if you don't mind

**Comment by jbkunst** [comment]
If you create and `id` field, why is a problem have same labels across the grouping vars?

**Comment by alexpghayes** [comment]
If the top level of the treemap has categories  in `{A, B}` and second level has categories in `{B, C}`, for cells on a third level of the treemap a parent id of `B1_B2` is ambiguous.

**Pull request merged**
