### PR TITLE
Allow multiple event types

### PR DESCRIPTION
**Pull request by martinjhnhadley**
The current hc_add_event_point implementation did not have good support for multiple event types, i.e. click and hover.

I have followed the convention of leaflet (http://rstudio.github.io/leaflet/shiny.html) in my PR.

Previously, 

output$my_hc <- renderHighchart()

input$my_hc would give event data

Now, there are objects per event type

input$my_hc_click
input$my_hc_mouseOver 

It may well prove useful to further extend this later

input$my_hc_click_marker
input$my_hc_click_line
etc

### CODE REVIEW

**Comment by jbkunst** [comment]
Nice! Thanks for this! I agree to follow the convention. Not sure why your commit change 96 files (all the roxygen) :P Not sure how only accpet the 1st commit. Can you _repull_ this only with the 1st/main commit please?

Thanks again :D

**Comment by martinjhnhadley** [comment]
Blooming roxygen, I thought it was being an awkward customer. Reverted that commit for you :)

I'm over the moon you had this queued up in devel as I needed it today for the first time. Very pleased to have helped a little with the package.

**Comment by jbkunst** [comment]
Not a little!

**Comment by jbkunst** [comment]
Added as ctb, thanks again!

**Pull request merged**
